### PR TITLE
Update ChibiOS to 20.3.3

### PR DESCRIPTION
**Pull request by davidlenfesty**
To be tested in HW before merging. Only made a PR so that it is a little more visible.

### CODE REVIEW

**Comment by minh7a6** [comment]
I would advise updating only to 20.3 as 21.6 does not have the community support (ChibiOS Contrib), also a lot of the libraries have changed, making the staging CMake needed to be changed as well

**Comment by davidlenfesty** [comment]
i c

**Comment by davidlenfesty** [comment]
Looks like this will need some amount of porting work - putting it on the backburner for now.

**Comment by minh7a6** [comment]
For porting ChibiOS, only the files in cfg folder needed to be upgraded. Also, we can copy the demo folder Makefile to run it. The application code does not need to be changed as API is identical throughout versions

**Comment by davidlenfesty** [comment]
If you want to do this, feel free to take over the branch, but I'm not spending any time on it for the next bit.

**Comment by minh7a6** [comment]
Sure

**Comment by minh7a6** [comment]
Motor Controller Firmware has been updated in order to work with ChibiOS 20

**Comment by minh7a6** [comment]
Blocked for testing

**Pull request merged**
